// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechResourceTrackerDataHandling.Models;

namespace TechResourceTrackerDataHandling.Migrations
{
    [DbContext(typeof(TechResourcesContext))]
    [Migration("20180913235300_SeedDataForTest")]
    partial class SeedDataForTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechResourceTrackerDataHandling.Models.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<int>("MediaTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Feed");

                    b.HasData(
                        new { Id = 1, Image = "https://static.giantbomb.com/uploads/original/11/110673/2894068-3836779617-28773.png", LastUpdated = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), MediaTypeId = 1, Title = "Giant BeastCast", Url = "https://www.giantbomb.com/podcast-xml/beastcast/" },
                        new { Id = 2, Image = "https://msdnshared.blob.core.windows.net/media/2017/10/Microsoft-favicon-cropped3.png", LastUpdated = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), MediaTypeId = 3, Title = ".NET Blog", Url = "https://blogs.msdn.microsoft.com/dotnet/feed/" },
                        new { Id = 3, Image = "https://yt3.ggpht.com/-mW8hwFBRUNs/AAAAAAAAAAI/AAAAAAAAAAA/jVL9TZ64o7A/s46-c-k-no-mo-rj-c0xffffff/photo.jpg", LastUpdated = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), MediaTypeId = 2, Title = "LearnCode.academy", Url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCVTlvUkGslCV_h-nSAId8Sw" }
                    );
                });

            modelBuilder.Entity("TechResourceTrackerDataHandling.Models.FeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime");

                    b.Property<int>("FeedId")
                        .HasColumnName("FeedID");

                    b.Property<string>("ItemContent")
                        .IsRequired();

                    b.Property<bool>("Seen");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.ToTable("FeedItem");

                    b.HasData(
                        new { Id = 1, DatePublished = new DateTime(2018, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), FeedId = 1, ItemContent = "We've got some updated impressions on Dreams and Spider-Man! Also, we explore some of the key differences between Gremlins and Gremlins 2, Abby's love of the Beach Boys, and more from the world of video games!", Seen = true, Title = "The Giant Beastcast - Episode 165", Url = "Ep165_-_The_Giant_Beastcast-07-19-2018-4836496507.mp3" },
                        new { Id = 2, DatePublished = new DateTime(2018, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), FeedId = 1, ItemContent = "More from the Warhammer 40K universe, the No Man's Sky universe, and the universe of things Alex hates talking about (mostly bathrooms). We've also got the news, your emails, and some stellar pun work in this extraordinary episode.", Seen = false, Title = "The Giant Beastcast - Episode 166", Url = "Ep166_-_The_Giant_Beastcast-07-26-2018-1461758603.mp3" },
                        new { Id = 3, DatePublished = new DateTime(2018, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), FeedId = 3, ItemContent = @"In part 2 of our machine learning crash course, we'll make a recommendation engine in the browser.
                        Here's the code! 
                        https://codepen.io/willrstern/pen/WzZqpd

                        We will make a recommendation engine example that fully runs in the browser with really good performance.  Artificial intelligence and machine learning are awesome new frontiers in computing and data science.  Web developers can use machine learning and artificial intelligence to solve problems in fun and unique ways.

                        Once we build a trained model using our neural network, we can quickly run thousands of possible options through our model to get ideal recommendations for our users.", Seen = true, Title = "Machine Learning Tutorial - Making a recommendation engine IN THE BROWSER", Url = "https://www.youtube.com/watch?v=lvzekeBQsSo" },
                        new { Id = 4, DatePublished = new DateTime(2018, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), FeedId = 3, ItemContent = @"GET THE SOURCE CODE: https://github.com/learncodeacademy/vue-tutorials

                        Now that we have the basics of Vue.js, let's scale it with a full build system and .vue single-file-components.  This is where Vue gets really fun in my opinion.

                        The Vue framework is extremely simple to learn and fun to use.
                        It's my tool of choice for small widgets and simple apps, but can easily scale to large application development.
                        Vuejs is also the best framework for new JS developers to learn when starting out.

                        Vue.js 1: https://www.youtube.com/watch?v=mZY1yyrlJWU&amp;index=1&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9
                        Vue.js 2: https://www.youtube.com/watch?v=h6lhOYv-QM4&amp;index=2&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9
                        Vue.js 3: https://www.youtube.com/watch?v=t0w2KLOLaTA&amp;index=3&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9
                        Vue.js 4: https://www.youtube.com/watch?v=1V9Lcnm1Dqw&amp;index=4&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9
                        Vue.js 5: https://www.youtube.com/watch?v=inJDWcHmsss&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9&amp;index=6
                        Vue.js 6: https://www.youtube.com/watch?v=Oyr5X5HwXhM&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9&amp;index=5
                        Vue.js 7: https://www.youtube.com/watch?v=IkcJ0YAiycQ&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9&amp;index=7
                        Vue.js 8: https://www.youtube.com/watch?v=mY2MiaYiSdw&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9&amp;index=8
                        Vue.js 9: https://www.youtube.com/watch?v=mS9-fTrgjrA&amp;list=PLoYCgNOIyGADZuvKJweutZDOO9VI9YiJ9&amp;index=9", Seen = true, Title = "Vue.js Tutorial #7 - Scaling Vue with Single File Components", Url = "https://www.youtube.com/watch?v=IkcJ0YAiycQ" }
                    );
                });

            modelBuilder.Entity("TechResourceTrackerDataHandling.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("Type")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MediaType");

                    b.HasData(
                        new { Id = 1, Type = "Audio" },
                        new { Id = 2, Type = "Video" },
                        new { Id = 3, Type = "Other" }
                    );
                });

            modelBuilder.Entity("TechResourceTrackerDataHandling.Models.Feed", b =>
                {
                    b.HasOne("TechResourceTrackerDataHandling.Models.MediaType", "MediaType")
                        .WithMany("Feed")
                        .HasForeignKey("MediaTypeId")
                        .HasConstraintName("FK_Feed_Feed");
                });

            modelBuilder.Entity("TechResourceTrackerDataHandling.Models.FeedItem", b =>
                {
                    b.HasOne("TechResourceTrackerDataHandling.Models.Feed", "Feed")
                        .WithMany("FeedItems")
                        .HasForeignKey("FeedId")
                        .HasConstraintName("FK_FeedItem_Feed");
                });
#pragma warning restore 612, 618
        }
    }
}
